test_debug_build:
  image: greenaddress/walletcrx@sha256:21451ff70e639a2a5c8fb8434b9593626c323a8ffd9372db5ee8bafc512de74f
  tags:
    - ga
  script:
    - cd $CI_PROJECT_DIR
    - npm i
    - npm run build
    - npm run test
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt --require-hashes
    - python render_templates.py -a ..
